package com.myspace.yearlyplansproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Users implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String userFirstName;
	@org.kie.api.definition.type.Label(value = "Last Name")
	private java.lang.String userLastName;
	@org.kie.api.definition.type.Label(value = "Email")
	private java.lang.String userEmail;
	@org.kie.api.definition.type.Label(value = "Phone")
	private java.lang.String userPhone;
	@org.kie.api.definition.type.Label(value = "Institution Name")
	private java.lang.String userInstitutionName;
	@org.kie.api.definition.type.Label(value = "Sector Name")
	private java.lang.String userSectorName;

	public Users() {
	}

	public java.lang.String getUserFirstName() {
		return this.userFirstName;
	}

	public void setUserFirstName(java.lang.String userFirstName) {
		this.userFirstName = userFirstName;
	}

	public java.lang.String getUserLastName() {
		return this.userLastName;
	}

	public void setUserLastName(java.lang.String userLastName) {
		this.userLastName = userLastName;
	}

	public java.lang.String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(java.lang.String userEmail) {
		this.userEmail = userEmail;
	}

	public java.lang.String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(java.lang.String userPhone) {
		this.userPhone = userPhone;
	}

	public java.lang.String getUserInstitutionName() {
		return this.userInstitutionName;
	}

	public void setUserInstitutionName(java.lang.String userInstitutionName) {
		this.userInstitutionName = userInstitutionName;
	}

	public java.lang.String getUserSectorName() {
		return this.userSectorName;
	}

	public void setUserSectorName(java.lang.String userSectorName) {
		this.userSectorName = userSectorName;
	}

	public Users(java.lang.String userFirstName, java.lang.String userLastName,
			java.lang.String userEmail, java.lang.String userPhone,
			java.lang.String userInstitutionName,
			java.lang.String userSectorName) {
		this.userFirstName = userFirstName;
		this.userLastName = userLastName;
		this.userEmail = userEmail;
		this.userPhone = userPhone;
		this.userInstitutionName = userInstitutionName;
		this.userSectorName = userSectorName;
	}

}