package com.myspace.yearlyplansproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class YearlyPlans implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("Assigned For Review")
	private java.lang.String assignedForReview;
	@org.kie.api.definition.type.Label("Date Created")
	private java.util.Date dateCreated;
	@org.kie.api.definition.type.Label("Date Modified")
	private java.util.Date dateModified;
	@org.kie.api.definition.type.Label("Deleted")
	private int deleted;
	@org.kie.api.definition.type.Label("Institution ")
	private java.lang.String institution;
	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Process Instance Id")
	private long planProcessInstanceId;
	@org.kie.api.definition.type.Label("Status")
	private java.lang.String status;
	@org.kie.api.definition.type.Label("Year")
	private int year;

	@org.kie.api.definition.type.Label("Created By")
	private java.lang.String createdBy;

	@org.kie.api.definition.type.Label("Modified By")
	private String modifiedBy;

	@org.kie.api.definition.type.Label("Industries")
	private java.util.List<java.lang.String> industriesId;

	@org.kie.api.definition.type.Label(value = "Next status")
	private java.lang.String nextStatus;

	public YearlyPlans() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getAssignedForReview() {
		return this.assignedForReview;
	}

	public void setAssignedForReview(java.lang.String assignedForReview) {
		this.assignedForReview = assignedForReview;
	}

	public java.util.Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(java.util.Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public java.util.Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(java.util.Date dateModified) {
		this.dateModified = dateModified;
	}

	public int getDeleted() {
		return this.deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

	public java.lang.String getInstitution() {
		return this.institution;
	}

	public void setInstitution(java.lang.String institution) {
		this.institution = institution;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public long getPlanProcessInstanceId() {
		return this.planProcessInstanceId;
	}

	public void setPlanProcessInstanceId(long planProcessInstanceId) {
		this.planProcessInstanceId = planProcessInstanceId;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public java.lang.String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(java.lang.String createdBy) {
		this.createdBy = createdBy;
	}

	public java.lang.String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(java.lang.String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public java.util.List<java.lang.String> getIndustriesId() {
		return this.industriesId;
	}

	public void setIndustriesId(java.util.List<java.lang.String> industriesId) {
		this.industriesId = industriesId;
	}

	public java.lang.String getNextStatus() {
		return this.nextStatus;
	}

	public void setNextStatus(java.lang.String nextStatus) {
		this.nextStatus = nextStatus;
	}

	public YearlyPlans(java.lang.String id, java.lang.String assignedForReview,
			java.util.Date dateCreated, java.util.Date dateModified,
			int deleted, java.lang.String institution, java.lang.String name,
			long planProcessInstanceId, java.lang.String status, int year,
			java.lang.String createdBy, java.lang.String modifiedBy,
			java.util.List<java.lang.String> industriesId,
			java.lang.String nextStatus) {
		this.id = id;
		this.assignedForReview = assignedForReview;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.deleted = deleted;
		this.institution = institution;
		this.name = name;
		this.planProcessInstanceId = planProcessInstanceId;
		this.status = status;
		this.year = year;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.industriesId = industriesId;
		this.nextStatus = nextStatus;
	}

}