package com.myspace.yearlyplansproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class YPtoIndustriesPlanned implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("Yearly Plan Id")
	private java.lang.String yearlyPlanId;
	@org.kie.api.definition.type.Label("Industry Id")
	private java.util.List<java.lang.String> industryId;

	@org.kie.api.definition.type.Label(value = "Available Quantity")
	private int crrmAvailableQuantity;

	public YPtoIndustriesPlanned() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getYearlyPlanId() {
		return this.yearlyPlanId;
	}

	public void setYearlyPlanId(java.lang.String yearlyPlanId) {
		this.yearlyPlanId = yearlyPlanId;
	}

	public java.util.List<java.lang.String> getIndustryId() {
		return this.industryId;
	}

	public void setIndustryId(java.util.List<java.lang.String> industryId) {
		this.industryId = industryId;
	}

	public int getCrrmAvailableQuantity() {
		return this.crrmAvailableQuantity;
	}

	public void setCrrmAvailableQuantity(int crrmAvailableQuantity) {
		this.crrmAvailableQuantity = crrmAvailableQuantity;
	}

	public YPtoIndustriesPlanned(java.lang.String id,
			java.lang.String yearlyPlanId,
			java.util.List<java.lang.String> industryId,
			int crrmAvailableQuantity) {
		this.id = id;
		this.yearlyPlanId = yearlyPlanId;
		this.industryId = industryId;
		this.crrmAvailableQuantity = crrmAvailableQuantity;
	}

}